// BGV micro_mul workload: ct_out = EvalMult(ct1, ct2)
// Homomorphic multiplication of two BGV ciphertexts packing 64-slot integer vectors.
// EvalMult includes relinearization (requires EvalMultKey generated by the caller).
// Self-registers into the global WorkloadRegistry at static init time.

#include "server/workload_registry.h"
#include "openfhe.h"

namespace {

using namespace lbcrypto;

tee::CC make_micro_mul_context() {
    CCParams<CryptoContextBGVRNS> params;
    params.SetMultiplicativeDepth(2);
    params.SetPlaintextModulus(65537);
    params.SetBatchSize(64);
    params.SetSecurityLevel(HEStd_128_classic);
    params.SetKeySwitchTechnique(BV);
    params.SetDigitSize(4);
    params.SetScalingTechnique(FIXEDMANUAL);
    params.SetFirstModSize(60);
    auto cc = GenCryptoContext(params);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    cc->Enable(ADVANCEDSHE);
    return cc;
}

tee::CT micro_mul_eval(tee::CC cc, const std::vector<tee::CT>& inputs) {
    if (inputs.size() != 2) {
        throw std::runtime_error("micro_mul requires exactly 2 input ciphertexts");
    }
    return cc->EvalMult(inputs[0], inputs[1]);
}

// Self-register at static initialization time.
// No gen_keys needed - EvalMultKey is generated by the caller (client always
// calls cc->EvalMultKeyGen after gen_keys hook).
[[maybe_unused]] tee::Register g_micro_mul_reg("micro_mul",
    tee::Workload{make_micro_mul_context, micro_mul_eval, nullptr});

}  // namespace
