// BGV small_dot workload: y = sum(w_i * x_i) mod 65537 for i=0..31.
// One input ciphertext x encoding a length-32 integer vector (slots 0..31).
// Fixed weight vector w[i] = i+1 embedded in the workload.
// Uses EvalMult(ct, ptxt_w) for element-wise products, then EvalSum to
// aggregate the 32 products into a single scalar in slot 0.
// Uses shared baseline context: ring=8192, depth=3, batch=4096, plaintext=65537.
// Self-registers into the global WorkloadRegistry at static init time.

#include "server/workload_registry.h"
#include "common/baseline_params.h"

#include <stdexcept>
#include <vector>

#include "openfhe.h"

namespace {

using namespace lbcrypto;

constexpr size_t kVecLen = 32;
constexpr int64_t kModulus = 65537;

// Fixed deterministic weight vector: w[i] = i+1 for i=0..31, 0 for i>=32.
// The trailing zeros ensure slots 32..4095 do not contribute to the sum.
std::vector<int64_t> make_weight_vector() {
    std::vector<int64_t> w(4096, 0);
    for (size_t i = 0; i < kVecLen; ++i) {
        w[i] = static_cast<int64_t>(i + 1);
    }
    return w;
}

tee::CC make_small_dot_context() {
    return make_baseline_bgvrns_context();
}

tee::CT small_dot_eval(tee::CC cc, const std::vector<tee::CT>& inputs) {
    if (inputs.empty()) {
        throw std::runtime_error(
            "small_dot workload requires at least 1 input ciphertext");
    }
    const auto& x = inputs[0];
    auto w = make_weight_vector();
    auto ptxt_w = cc->MakePackedPlaintext(w);
    // Element-wise product: slot i = w[i] * x[i] (mod 65537).
    // BGV plaintext-ciphertext multiplication consumes one multiplicative level.
    auto ct_prod = cc->EvalMult(x, ptxt_w);
    // Aggregate the 32 element-wise products into a single scalar in slot 0.
    // EvalSum(ct, n) performs a log2(n)-step tree reduction using rotations
    // by n/2, n/4, ..., 1; after all steps slot 0 holds sum(ct[0..n-1]).
    // Rotations wrap at ringDim (8192), NOT batchSize (4096), so only slot 0
    // is guaranteed to receive the full sum. Slots 32..4095 of ct_prod are zero
    // (w[i]=0 for i>=32), so summing the first 32 slots (kVecLen) is sufficient
    // and more efficient than summing all 4096. EvalSum uses rotation keys
    // (powers of 2) generated by EvalSumKeyGen; it does not consume
    // multiplicative depth.
    return cc->EvalSum(ct_prod, kVecLen);
}

// gen_keys hook: generate EvalSum keys (automorphism/rotation keys for all
// powers of 2 up to batchSize). Required by cc->EvalSum.
void small_dot_gen_keys(tee::CC cc,
                        const lbcrypto::KeyPair<lbcrypto::DCRTPoly>& kp) {
    cc->EvalSumKeyGen(kp.secretKey);
}

// Self-register at static initialization time.
[[maybe_unused]] tee::Register g_small_dot_reg(
    "small",
    tee::Workload{make_small_dot_context, small_dot_eval, small_dot_gen_keys});

}  // namespace
