// BGV small_dot workload: y = sum(w_i * x_i) mod 65537 for i=0..31.
// One input ciphertext x encoding a length-32 integer vector (slots 0..31).
// Fixed weight vector w[i] = i+1 embedded in the workload.
// Uses EvalMult(ct, ptxt_w) for element-wise products, then EvalSum to
// aggregate the 32 products into a single scalar in slot 0.
// NOTE: EvalSum uses a log-tree reduction with rotations that wrap at
// ringDim (8192), not batchSize (64). Only slot 0 is guaranteed to hold
// the full dot product; other slots contain partial sums and must NOT be
// relied upon. BGV params: multiplicativeDepth=2, plaintextModulus=65537,
// batchSize=64, FIXEDMANUAL, BV key switching.
// Self-registers into the global WorkloadRegistry at static init time.

#include "server/workload_registry.h"

#include <stdexcept>
#include <vector>

#include "openfhe.h"

namespace {

using namespace lbcrypto;

constexpr size_t kVecLen = 32;
constexpr size_t kBatchSize = 64;
constexpr int64_t kModulus = 65537;

// Fixed deterministic weight vector: w[i] = i+1 for i=0..31, 0 for i>=32.
// The trailing zeros ensure slots 32..63 do not contribute to the sum.
std::vector<int64_t> make_weight_vector() {
    std::vector<int64_t> w(kBatchSize, 0);
    for (size_t i = 0; i < kVecLen; ++i) {
        w[i] = static_cast<int64_t>(i + 1);
    }
    return w;
}

tee::CC make_small_dot_context() {
    CCParams<CryptoContextBGVRNS> params;
    params.SetMultiplicativeDepth(2);
    params.SetPlaintextModulus(kModulus);
    params.SetBatchSize(kBatchSize);
    params.SetSecurityLevel(HEStd_128_classic);
    params.SetKeySwitchTechnique(BV);
    params.SetDigitSize(4);
    params.SetScalingTechnique(FIXEDMANUAL);
    params.SetFirstModSize(60);
    auto cc = GenCryptoContext(params);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    cc->Enable(ADVANCEDSHE);  // Required for EvalSumKeyGen / EvalSum.
    return cc;
}

tee::CT small_dot_eval(tee::CC cc, const std::vector<tee::CT>& inputs) {
    if (inputs.empty()) {
        throw std::runtime_error(
            "small_dot workload requires at least 1 input ciphertext");
    }
    const auto& x = inputs[0];
    auto w = make_weight_vector();
    auto ptxt_w = cc->MakePackedPlaintext(w);
    // Element-wise product: slot i = w[i] * x[i] (mod 65537).
    // BGV plaintext-ciphertext multiplication consumes one multiplicative
    // level; multiplicativeDepth=2 provides sufficient modulus-chain headroom.
    auto ct_prod = cc->EvalMult(x, ptxt_w);
    // Aggregate the 32 element-wise products into a single scalar in slot 0.
    // EvalSum(ct, n) performs a log2(n)-step tree reduction using rotations
    // by n/2, n/4, ..., 1; after all steps slot 0 holds sum(ct[0..n-1]).
    // Rotations wrap at ringDim (8192), NOT batchSize (64), so only slot 0
    // is guaranteed to receive the full sum. Slots 32..63 of ct_prod are zero
    // (w[i]=0 for i>=32), so summing the first 32 slots (kVecLen) is sufficient
    // and more efficient than summing all 64 (kBatchSize). EvalSum uses
    // rotation keys (powers of 2) generated by EvalSumKeyGen; it does not
    // consume multiplicative depth.
    return cc->EvalSum(ct_prod, kVecLen);
}

// gen_keys hook: generate EvalSum keys (automorphism/rotation keys for all
// powers of 2 up to batchSize). Required by cc->EvalSum.
void small_dot_gen_keys(tee::CC cc,
                        const lbcrypto::KeyPair<lbcrypto::DCRTPoly>& kp) {
    cc->EvalSumKeyGen(kp.secretKey);
}

// Self-register at static initialization time.
[[maybe_unused]] tee::Register g_small_dot_reg(
    "small",
    tee::Workload{make_small_dot_context, small_dot_eval, small_dot_gen_keys});

}  // namespace
