// BGV toy workload: y = (c1 * c2) mod 65537
// Multiplies two BGV ciphertexts packing length-32 integer vectors.
// Self-registers into the global WorkloadRegistry at static init time.

#include "server/workload_registry.h"
#include "openfhe.h"

namespace {

using namespace lbcrypto;

tee::CC make_toy_context() {
    CCParams<CryptoContextBGVRNS> params;
    params.SetMultiplicativeDepth(1);
    params.SetPlaintextModulus(65537);
    params.SetBatchSize(64);
    params.SetSecurityLevel(HEStd_128_classic);
    params.SetKeySwitchTechnique(BV);
    params.SetDigitSize(4);
    params.SetScalingTechnique(FIXEDMANUAL);
    params.SetFirstModSize(60);
    auto cc = GenCryptoContext(params);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    return cc;
}

tee::CT toy_eval(tee::CC cc, const std::vector<tee::CT>& inputs) {
    if (inputs.size() != 2) {
        throw std::runtime_error("toy requires exactly 2 input ciphertexts");
    }
    return cc->EvalMult(inputs[0], inputs[1]);
}

// Self-register at static initialization time.
// No gen_keys needed — EvalMultKey is generated by the caller.
[[maybe_unused]] tee::Register g_toy_reg("toy",
    tee::Workload{make_toy_context, toy_eval, nullptr});

}  // namespace