// BGV-Mul-4K workload: ct_out = EvalMultNoRelin(ct1, ct2)
// Homomorphic multiplication of two BGV ciphertexts packing 4096-slot integer vectors.
// Uses EvalMultNoRelin (no relinearization) - see toy.cpp for rationale.
// Uses the shared baseline context (ringDim=8192, batchSize=4096, depth=4).
// Self-registers into the global WorkloadRegistry at static init time.

#include "common/baseline_params.h"
#include "server/workload_registry.h"
#include "openfhe.h"
#include "proofsystem/proofsystem_libsnark.h"

namespace {

using namespace lbcrypto;

zk::CT bgv_mul_4k_eval(zk::CC cc, const std::vector<zk::CT>& inputs) {
    if (inputs.size() != 2) {
        throw std::runtime_error("BGV-Mul-4K requires exactly 2 input ciphertexts");
    }
    return cc->EvalMultNoRelin(inputs[0], inputs[1]);
}

zk::CT bgv_mul_4k_eval_zk(LibsnarkProofSystem& ps, std::vector<zk::CT>& inputs) {
    if (inputs.size() != 2) {
        throw std::runtime_error("BGV-Mul-4K requires exactly 2 input ciphertexts");
    }
    ps.PublicInput(inputs[0]);
    ps.PublicInput(inputs[1]);
    return ps.EvalMultNoRelin(inputs[0], inputs[1]);
}

// Self-register at static initialization time.
// Uses the shared baseline context (batchSize=4096, ringDim=8192, depth=4).
// No gen_keys needed - EvalMultKey is generated by the caller.
[[maybe_unused]] zk::Register g_bgv_mul_4k_reg("BGV-Mul-4K",
    zk::Workload{make_baseline_bgvrns_context, bgv_mul_4k_eval, nullptr, bgv_mul_4k_eval_zk});

}  // namespace
