// BGV toy workload: y = (c1 * c2) mod 65537
// Multiplies two BGV ciphertexts packing length-32 integer vectors
// (zero-padded to batchSize=4096). Uses the shared baseline context.
// Self-registers into the global WorkloadRegistry at static init time.
//
// NOTE: eval and eval_zk both use EvalMultNoRelin (no relinearization).
// zkOpenFHE's RelinearizeConstraint is buggy: the relin unit test in
// zkOpenFHE crashes, and at production scale it produces unsatisfied
// constraint systems. EvalMultNoRelin produces a 3-element ciphertext
// that decrypts correctly; the ZK proof covers the multiplication only.

#include "common/baseline_params.h"
#include "server/workload_registry.h"
#include "openfhe.h"
#include "proofsystem/proofsystem_libsnark.h"

namespace {

using namespace lbcrypto;

zk::CT toy_eval(zk::CC cc, const std::vector<zk::CT>& inputs) {
    if (inputs.size() != 2) {
        throw std::runtime_error("toy requires exactly 2 input ciphertexts");
    }
    return cc->EvalMultNoRelin(inputs[0], inputs[1]);
}

zk::CT toy_eval_zk(LibsnarkProofSystem& ps, std::vector<zk::CT>& inputs) {
    if (inputs.size() != 2) {
        throw std::runtime_error("toy requires exactly 2 input ciphertexts");
    }
    ps.PublicInput(inputs[0]);
    ps.PublicInput(inputs[1]);
    return ps.EvalMultNoRelin(inputs[0], inputs[1]);
}

// Self-register at static initialization time.
// Uses the shared baseline context (batchSize=4096, ringDim=8192, depth=4).
// No gen_keys needed - EvalMultKey is generated by the caller.
[[maybe_unused]] zk::Register g_toy_reg("toy",
    zk::Workload{make_baseline_bgvrns_context, toy_eval, nullptr, toy_eval_zk});

}  // namespace
