// BGV toy workload: y = (c1 * c2) mod 65537
// Multiplies two BGV ciphertexts packing length-32 integer vectors
// (zero-padded to batchSize=4096). Uses the shared baseline context.
// Self-registers into the global WorkloadRegistry at static init time.

#include "common/baseline_params.h"
#include "server/workload_registry.h"
#include "openfhe.h"

namespace {

using namespace lbcrypto;

zk::CT toy_eval(zk::CC cc, const std::vector<zk::CT>& inputs) {
    if (inputs.size() != 2) {
        throw std::runtime_error("toy requires exactly 2 input ciphertexts");
    }
    return cc->EvalMult(inputs[0], inputs[1]);
}

// Self-register at static initialization time.
// Uses the shared baseline context (batchSize=4096, ringDim=8192, depth=4).
// No gen_keys needed — EvalMultKey is generated by the caller.
[[maybe_unused]] zk::Register g_toy_reg("toy",
    zk::Workload{make_baseline_bgvrns_context, toy_eval, nullptr});

}  // namespace